import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Disc3, Lightbulb, Mic2, Sparkles } from "lucide-react";
import { Reveal } from "@/components/reveal";
import { SectionHeading } from "@/components/section-heading";
import { equipment } from "@/lib/equipment";
import { assetPath } from "@/lib/paths";

export const metadata: Metadata = { title: "DJ & Event Equipment Hire", description: "Hire professional DJ controllers, wireless microphones and event lighting from TWB Productions in Cape Town.", alternates: { canonical: "/equipment" } };
const categories = [{ icon: Disc3, title: "DJ systems", text: "Professional all-in-one controllers and mixer systems for reliable booth performance." }, { icon: Mic2, title: "Wireless audio", text: "Clean, dependable voice systems for speeches, ceremonies, MCs and panels." }, { icon: Lightbulb, title: "Event lighting", text: "Moving fixtures and LED washes for atmosphere, stages and dance floors." }];

export default function EquipmentPage() {
  return <main>
    <section className="relative min-h-[72vh] overflow-hidden pt-20"><Image src={assetPath("/assets/equipment-hero-background.png")} alt="TWB Productions DJ and event equipment" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,2,8,.94),rgba(5,2,8,.35)),linear-gradient(0deg,#050208,transparent_60%)]" /><div className="grid-fade absolute inset-0" /><div className="site-shell relative z-10 flex min-h-[72vh] items-end pb-16"><Reveal><p className="eyebrow">Equipment hire · Cape Town</p><h1 className="display gradient-text mt-5 max-w-5xl text-[clamp(4.5rem,12vw,9.5rem)]">The right kit for the room.</h1><p className="mt-6 max-w-xl text-base leading-7 text-white/65">Event-ready DJ, wireless audio and lighting equipment—available on its own or as part of a complete TWB production package.</p><a className="button-primary mt-8" href="#catalogue">View the catalogue <ArrowRight size={16} /></a></Reveal></div></section>
    <section className="section-pad site-shell"><SectionHeading eyebrow="Built for show day" title="Professional gear. Proper support." copy="Tell us the date, venue and guest count. We’ll help match the equipment to the room and can include delivery, setup and technical operation." /><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 md:grid-cols-3">{categories.map(({ icon: Icon, title, text }, index) => <Reveal key={title} delay={index * .06} className="bg-ink p-8"><Icon className="text-pink" size={25} /><h2 className="display mt-12 text-4xl">{title}</h2><p className="mt-4 text-sm leading-7 text-white/50">{text}</p></Reveal>)}</div></section>
    <section id="catalogue" className="section-pad border-y border-white/8 bg-panel/35"><div className="site-shell"><SectionHeading eyebrow="Available equipment" title="Choose your setup." /><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{equipment.map((item, index) => <Reveal key={item.slug} delay={(index % 3) * .05}><Link href={`/equipment/${item.slug}`} className="group block overflow-hidden rounded-2xl border border-white/10 bg-ink"><div className="relative aspect-square overflow-hidden bg-[radial-gradient(circle,rgba(139,92,246,.18),transparent_65%)]"><Image src={item.image} alt={item.alt} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-contain p-8 transition duration-500 group-hover:scale-105" /></div><div className="border-t border-white/10 p-6"><p className="eyebrow">{item.category}</p><div className="mt-3 flex items-end justify-between gap-4"><h2 className="display text-3xl">{item.name}</h2><ArrowRight className="shrink-0 text-white/35 transition group-hover:translate-x-1 group-hover:text-cyan" size={18} /></div></div></Link></Reveal>)}</div></div></section>
    <section className="section-pad site-shell"><div className="glass relative overflow-hidden rounded-3xl p-8 sm:p-12"><Sparkles className="absolute right-8 top-8 text-pink/50" /><p className="eyebrow">Need a complete package?</p><h2 className="display mt-5 max-w-3xl text-5xl sm:text-7xl">Let us build the booth, stage and dance floor together.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-white/55">Combine equipment hire with TWB DJs, engineering, setup and show-day production.</p><Link href="/book" className="button-primary mt-8">Request a hire quote <ArrowRight size={16} /></Link></div></section>
  </main>;
}
